```{r}
library(broom) #going to use broom for glancing
model = lm(kcal ~ carb_intake, data=data) #so first run the linear regression
model_int = model[[1]][[1]] #extracting interecept
model_slope = model[[1]][[2]] #and extracting slope
r2 = glance(model)[[1]][[1]] #then extract r squared

data |>
  ggplot(aes(x=carb_intake, y=kcal)) +
    geom_point(color="darkblue", size=0.5) + #so its easier to see
    geom_abline(slope = model_slope, intercept = model_int, color="red") + #using our model stuff
    theme_minimal() +
    labs(title="There is a positive correlation between Carbs Intake and Energy Intake",
      subtitle=paste0("y = ", round(model_slope, 2), "x + ", round(model_int, 2), ", r^2 = ", round(r2, 2)),
      x="Day 1 Carbohydrate Intake in g",
      y="Day 1 Energy Intake in kcal")
```

This figures makes use of a scatterplot and trend line to visualize possible correlations between carbohydrate intake in grams and energy intake in kcals of participants in the NHANES study. As our question looks at possible relationships between increasing carbohydrate intake and increased energy intake, creating a scatter plot could help us see the general trend between these two variables and determine whether a relationship occurs, as well as which direction it is in. The linear regression model has a slope of 6.81 and an intercept of 460.94. The intercept tells us that when a participant's carbohydrate intake on Day 1 of the survey was 0 g, their predicted energy intake for that day would be 460.94 kcals. The slope tells us that for every one gram increase in carbohydrate intake, our model predicts an increase in the energy intake by 6.81 kcals. The r^2 value derived was 0.73, telling us that around 73% of variability in the Day 1 energy intake could be explained by carbohydrate intake on that same day.